
# set the programming language to java:
language: java

# test for these JDK versions and environments
jdk:
   - oraclejdk8

script: 
   - mvn clean verify
   - mvn cobertura:cobertura coveralls:report
   
after_success:
   - mvn clean cobertura:cobertura coveralls:report