
# set the programming language to java:
language: java

# test for these JDK versions and environments
jdk:
   - oraclejdk8

# container-based build:
sudo: required

script: 
   - mvn clean verify
   
after_success:
   - mvn clean test saga:coverage cobertura:cobertura coveralls:report